# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ced78780dc2921c6ee8282f018137199d49f55e8db0ec29b960995989c467597d60537ca5bd2b929af66b304c5ba8044bd3cc5e0492c651353e33ec5db16c91

test:
  secret_key_base: eb8eff73cef079ab8d7aaea1921446dfbb8e652bfdc3ccc14a0a05393d0f3898a2fb36961964ba092b48f3fdb6c0b95ce9460d1facf5a834beb0ff7e354d934a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
